language: python
python:
  - "2.7"
  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install: 
  - pip install -r requirements.txt
script: 
  - python -m unittest discover
  - python setup.py test
  - python --version
  - python setup.py develop
  - prvsn init -b runbook && test -f runbook/roles/base/main.py
  - prvsn -b ./runbook -r base | grep Hello
  - prvsn provision -b ./runbook -r base | grep Hello
  - prvsn package -b ./runbook -r base && test -f package.pyz
  - prvsn package -b ./runbook -r base -o package2.pyz && test -f package2.pyz
  - python package.pyz | grep Hello