language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install: 
  - pip install -r requirements.txt
script: 
  - python -m unittest discover
  - python setup.py test
  - python3 scripts/prvsn provision -b tests/runbook -r echo
  - python3 scripts/prvsn init -b tests/runbook2 -r echo
  - python3 scripts/prvsn package -b tests/runbook -r echo -o tests/package.pyz && python3 tests/package.pyz
